CREATE TABLE Campañas (
    IDCampaña INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    IDUsuario INT(6) UNSIGNED,
    IDPlantilla INT(6) UNSIGNED NULL,
    Nombre VARCHAR(100) NOT NULL,
    Descripción TEXT,
    FechaInicio TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FechaFin TIMESTAMP,
    FOREIGN KEY (IDUsuario) REFERENCES Usuarios(ID),
    FOREIGN KEY (IDPlantilla) REFERENCES PlantillasCorreo(IDPlantilla)
);